# Oauth configuration file, using YAML and the 'global' gem
# See http://railsware.com/blog/2013/07/26/globalize-your-configuration
# See http://railsware.com/blog/2013/10/16/rails-configuration-in-the-proper-way/

# OAuth Key    = policy-wizard

development:
  oauth_secret: secret

testing:
  oauth_secret: secret

production:
  oauth_secret: <%= ENV['POLICY_WIZARD_OAUTH_SECRET'] %>
