# Oauth configuration file, using YAML and the 'global' gem
# See http://railsware.com/blog/2013/07/26/globalize-your-configuration
# See http://railsware.com/blog/2013/10/16/rails-configuration-in-the-proper-way/

# OAuth Key    = policy-wizard
# OAuth Secret = Th!s1sTh3Ac&d3m1cP0l!c%W1z4rd

development:
  oauth_secret: secret

testing:
  oauth_secret: secret

production:
  oauth_secret: <%= ENV['POLICY_WIZARD_OAUTH_SECRET'] %>